Style/FrozenStringLiteralComment:
  Enabled: false
Style/BlockComments:
  Enabled: false
Style/AsciiComments:
  Enabled: false
AllCops:
  Exclude:
    - 'bin/*'
Documentation:
  Enabled: false
Metrics/LineLength:
  Max: 120